
export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About Us" },
  { href: "/#verticals", label: "Verticals" },
  { href: "/products", label: "Products & Services" },
  { href: "/partners", label: "Partners" },
  { href: "/contact", label: "Contact" },
];

export const PARTNER_LOGOS = [
  { src: '/images/logos/canon.png', alt: 'Canon', dataAiHint: 'logo technology' },
  { src: 'https://placehold.co/150x60/EFEFEF/333366?text=Onyx', alt: 'Onyx', dataAiHint: 'logo electronics' },
  { src: '/images/logos/b-tec.png', alt: 'B-Tec', dataAiHint: 'logo industrial' },
  { src: '/images/logos/smartpower-automation.png', alt: 'Smartpower Automation', dataAiHint: 'logo automation' },
  { src: '/images/logos/phoenix-contact.png', alt: 'Phoenix Contact', dataAiHint: 'logo electronics' },
  { src: '/images/logos/grainger.png', alt: 'Grainger', dataAiHint: 'logo industrial supply' },
  { src: '/images/logos/technofront-electronics.jpg', alt: 'Technofront Electronics', dataAiHint: 'logo electronics' },
];

export const CLIENT_LOGOS = [
  { src: '/images/key_accounts/drdo-logo.jpeg', alt: 'DRDO', dataAiHint: 'logo defence research' },
  { src: '/images/key_accounts/ecil-logo.jpeg', alt: 'ECIL', dataAiHint: 'logo aerospace' },
  { src: '/images/key_accounts/NSTL-LOGO.jpeg', alt: 'NSTL', dataAiHint: 'logo space research' },
  { src: '/images/key_accounts/JNTUH-LOGO.jpg', alt: 'JNTUH', dataAiHint: 'logo university' },
  { src: '/images/key_accounts/BARC-LOGO.png', alt: 'BARC', dataAiHint: 'logo atomic research' },
  { src: '/images/key_accounts/DLRL.jpg', alt: 'DLRL', dataAiHint: 'logo defence lab' },
  { src: '/images/key_accounts/BHARAT-ELECTRONICS-LOGO.png', alt: 'BHARAT-ELECTRONICS', dataAiHint: 'logo defence' },
  { src: '/images/key_accounts/ISRO-LOGO.png', alt: 'ISRO', dataAiHint: 'logo space agency' },
  { src: '/images/key_accounts/BHARAT-DYNAMICS-LIMITED-LOGO.png', alt: 'BHARAT-DYNAMICS-LIMITED', dataAiHint: 'logo defence systems' },
  { src: '/images/key_accounts/HAL-LOGO.png', alt: 'HAL', dataAiHint: 'logo aeronautics' },
  { src: '/images/key_accounts/TECH-MAHENDRA-LOGO.PNG', alt: 'Tech Mahindra', dataAiHint: 'logo technology services' },
  { src: '/images/key_accounts/Qualcomm-Logo.png', alt: 'Qualcomm', dataAiHint: 'logo semiconductor' },
  { src: '/images/key_accounts/INDIAN-NAVY-LOGO.jpg', alt: 'Indian Navy', dataAiHint: 'logo navy' },
  { src: '/images/key_accounts/TSGENCO-logo.png', alt: 'TSGENCO', dataAiHint: 'logo power generation' },
  { src: '/images/key_accounts/INCOIS-LOGO.jpeg', alt: 'INCOIS', dataAiHint: 'logo ocean information' },
  { src: '/images/key_accounts/NARL-LOGO.jpeg', alt: 'NARL', dataAiHint: 'logo atmospheric research' },
  { src: '/images/key_accounts/NGRI-LOGO.png', alt: 'NGRI', dataAiHint: 'logo geophysics' },
  { src: '/images/key_accounts/Indian-Railway.jpg', alt: 'Indian Railways', dataAiHint: 'logo indian railways' },
];

export const RESELLING_BRANDS = [
    { src: '/images/reselling-brands/AbraconLogos.jpg', alt: 'Abracon', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/Altera_logo.png', alt: 'Altera', dataAiHint: 'logo programmable logic' },
    { src: '/images/reselling-brands/ampelo.png', alt: 'Amphenol', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/ANALOG-DEVICES-LOGO.jpg', alt: 'Analog Devices', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/Atmel_logo.png', alt: 'Atmel', dataAiHint: 'logo microcontroller' },
    { src: '/images/reselling-brands/BELDEN-LOGO.png', alt: 'Belden', dataAiHint: 'logo cable' },
    { src: '/images/reselling-brands/bourns-logo.png', alt: 'Bourns', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/cinch-connectivity.png', alt: 'Cinch Connectivity', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/cooper-bussmann-logo.png', alt: 'Cooper Bussmann', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/cosel.png', alt: 'Cosel', dataAiHint: 'logo power supply' },
    { src: '/images/reselling-brands/crystek.png', alt: 'Crystek', dataAiHint: 'logo frequency control' },
    { src: '/images/reselling-brands/Cypress_Logo.jpg', alt: 'Cypress', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/delta.jpg', alt: 'Delta', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/DMC-Logo.png', alt: 'DMC', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/eaton-logo.png', alt: 'Eaton', dataAiHint: 'logo power management' },
    { src: '/images/reselling-brands/EMBPAPST-LOGO.png', alt: 'ebm-papst', dataAiHint: 'logo fans motors' },
    { src: '/images/reselling-brands/FESTO-LOGO.png', alt: 'Festo', dataAiHint: 'logo automation' },
    { src: '/images/reselling-brands/freescale-LOGO.png', alt: 'Freescale', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/GLENAIR-LOGO.JPG', alt: 'Glenair', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/hammondmfg-LOGO.jpg', alt: 'Hammond Mfg', dataAiHint: 'logo electrical enclosures' },
    { src: '/images/reselling-brands/harwin-logo.jpg', alt: 'Harwin', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/Honeywell-logo.png', alt: 'Honeywell', dataAiHint: 'logo technology' },
    { src: '/images/reselling-brands/Infineon-Technologies-LOGO.png', alt: 'Infineon', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/KEMET-LOGO.png', alt: 'KEMET', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/LITTELFUSE-LOGO.png', alt: 'Littelfuse', dataAiHint: 'logo circuit protection' },
    { src: '/images/reselling-brands/MOLEX-LOGO.jpg', alt: 'Molex', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/MURATA-LOGO.png', alt: 'Murata', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/NEXPERIA-LOGO.png', alt: 'Nexperia', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/NXP_logo.jpg', alt: 'NXP', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/on-semiconductor-LOGO.jpg', alt: 'ON Semiconductor', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/Raychem.jpg', alt: 'Raychem', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/renesas-logo.png', alt: 'Renesas', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/samtec-logo.png', alt: 'Samtec', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/SouriauLogo.png', alt: 'Souriau', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/STM-LOGO.png', alt: 'STMicroelectronics', dataAiHint: 'logo semiconductor' },
    { src: '/images/reselling-brands/TDK_logo.jpg', alt: 'TDK', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/TE-CONNECTIVITY-LOGO.jpeg', alt: 'TE Connectivity', dataAiHint: 'logo connectors' },
    { src: '/images/reselling-brands/texasinstruments.png', alt: 'Texas Instruments', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/Traco-Poiwer_Logo.jpg', alt: 'Traco Power', dataAiHint: 'logo power supply' },
    { src: '/images/reselling-brands/VICOR-log.jpg', alt: 'Vicor', dataAiHint: 'logo power' },
    { src: '/images/reselling-brands/Vishay_Logo.png', alt: 'Vishay', dataAiHint: 'logo electronics' },
    { src: '/images/reselling-brands/Wago-logo.png', alt: 'Wago', dataAiHint: 'logo electrical' },
    { src: '/images/reselling-brands/Xp-Power-LOGO.png', alt: 'XP Power', dataAiHint: 'logo power' },
    { src: '/images/reselling-brands/yageo-logo.jpg', alt: 'Yageo', dataAiHint: 'logo passive components' },
];

export const PRODUCTS = [];
    
    
